AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*'
